version: "3"

services:
  nginx:
    # Note : Only nginx:alpine supports bcrypt.
    # If you don't need to use bcrypt, you can use a different tag.
    # Ref. https://github.com/nginxinc/docker-nginx/issues/29
    image: "nginx:alpine"
    ports:
      - 443:443
    volumes:
      - ./auth:/etc/nginx/conf.d
      - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gui:/usr/share/nginx/gui:ro

  registry:
    image: registry:2
    hostname: registry
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./data:/var/lib/registry

  ldap:
    image: osixia/openldap:latest
    ports:
      - 389:389
    hostname: ldap
  
  # ldapadmin:
  #   image: osixia/phpldapadmin
  #   hostname: phpldapadmin
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS: ldap
  #   ports:
  #     - 6443:443

  # login:
  #   image: ldapauth
  #   volumes:
  #     - ./ldapauth:/usr/src/app
  #   ports:
  #     - 3000:3000