version: "3"

services:
  nginx:
    image: "nginx:alpine"
    ports:
      - 443:443
    volumes:
      - ./auth:/etc/nginx/conf.d
      - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gui:/usr/share/nginx/gui:ro

  registry:
    image: registry:2
    hostname: registry
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./data:/var/lib/registry
      - ./auth/config-registry.yml:/etc/docker/registry/config.yml

  ldap:
    image: osixia/openldap:latest
    ports:
      - 389:389
    hostname: ldap
